Fieldset & Legend Nanny Accessibility Update
InformedSolutions/OFS-MORE-Nanny-Website pull request #279
Opened 2021-09-15 12:57 UTC by AustenCWells

## Description

[Goes here]

## Todo's before PR

- [ ] Branch has been rebased against develop
- [ ] Unit tests passed (`make test`)
- [ ] Selenium tests have passed
- [ ] PR named appropriately - see [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [ ] PR description describes the overall goals of PR commits
- [ ] Templates have been checked against the relevant user-story

## Migrations

- [ ] Null fields in models specifies default value
- [ ] You generated and applied migrations (`make migrate`)
- [ ] You updated fixtures (`make export`)

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [ ] Specified reviewers (even if it's yourself)
- [ ] Specified assignees (those who'll merge)
- [ ] Specified labels

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [ ] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

2021-09-15 14:30 UTC, jenniferbrown94 requested changes

2021-09-15 14:30 UTC, jenniferbrown94 commented on application/presentation/childcare_address/templates/childcare-address-lookup.html
> +    <legend class="Select Childcare Address">
you don't need this class here, same for all the legends added below

2021-09-15 14:30 UTC, jenniferbrown94 commented on application/presentation/childcare_address/templates/childcare-address-lookup.html
> +    <legend class="Select Childcare Address">
You don't need a legend and fieldset here as there is only one question on the page, and the question already has a label.

2021-09-16 15:19 UTC, AustenCWells commented on application/presentation/childcare_address/templates/childcare-address-lookup.html
> +    <legend class="Select Childcare Address">
Hi Jenny, I've updated the branch with these changes. This is now ready for another review. Thank you

2021-09-20 10:25 UTC, jenniferbrown94 approved these changes

2021-10-01 09:13 UTC, closed without merging